FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# Определяем переменные окружения
ENV thread_quantity=10
ENV request_delay=10000

CMD ["python3", "client.py"]