FROM ubuntu:latest

RUN apt-get update -qy
RUN apt-get install -qy python3.11 python3-pip python3.11-dev

COPY ./ /web_app
COPY ./requirements.txt /web_app
WORKDIR /web_app
RUN pip install -r requirements.txt

CMD ["uvicorn", "web:app", "--host", "0.0.0.0", "--port", "8000"]